# Generated by Django 5.0.2 on 2024-02-19 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_post', '0003_alter_carposts_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='posts',
            new_name='cars',
        ),
    ]
